CXX = g++
OBJS = main.cpp Assalariado.cpp Comissionado.cpp Funcionario.cpp FuncionarioNaoExisteException.cpp Horista.cpp OrcamentoEstouradoException.cpp SistemaGerenciarFolha.cpp 
TARGET = main

$(TARGET) : $(OBJS)
	$(CXX) -o $(TARGET) $(OBJS)